version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_ACCESS_KEY_SECRET=test
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - /var/lib/localstack
      - ./localstack:/var/lib/localstack
  sftp:
    container_name: local-sftp
    build: 
      context: .
    environment:
      - ROOT_PASSWORD=password
      - PASSWORD=password
    ports: 
      - '32768:22'
    volumes: 
      - /var/run/sshd
  
volumes:
  localstack: